### PR TITLE
Feature/native security policygen compare

### PR DESCRIPTION
**Pull request by mvo5**
[Based on feature/native-security-policygen-add-hwaccess so easiest to compare with e.g. https://github.com/mvo5/snappy/compare/feature/native-security-policygen-add-hwaccess...feature/native-security-policygen-compare]

This branch adds a new "snappy policygen --compare" that will compare the generated policy with the on-disk policy and error if they are different. This branch is mostly to ask if the approach is correct. if so I will add more tests. There is an open question about "apparmor_profile -p"  that apparently needs to be taken into account here as well. I don't know enough about this yet and will add this in a followup branch most likely.

### CODE REVIEW

**Comment by jdstrand** [comment]
Something isn't quite right here. If I install hello-world, then update /var/lib/apparmor/profiles/click_hello-world.canonical_sh_1.0.18 to have an additional rule, then this isn't returning non-zero:
$ sudo /tmp/snappy policygen --compare /apps/hello-world.canonical/current/meta/package.yaml  && echo "$?"
0

To ease working on the branch, I am going to commit it to the security.cleanup branch though.

**Comment by jdstrand** [comment]
The idea with apparmor_parser -p is that *if* apparmor changed, then if the policy in /var/lib/snappy/apparmor/profiles is the *same* as what policy generation would create, then do a 'deep check' and see if 'apparmor_parser -p <old>' and 'apparmor_parser -p <current>' are different. This is because the parser or the included abstractions might have changed and there is no way to detect that without apparmor_parser -p (not, apparmor_parser -p is not a policy compile, it is a fast preprocessor that can be thought of as a normalized concatenation of the specified policy and all of the included abstractions). The only wrinkle with this is that '<old>' must be saved off as part as policy generation so that it can be compared to later.

Alternatively, we could unconditionally regenerate all policy if the apparmor version changed, but this is expensive on armhf with lots of policy (eg, the future ubuntu-personal easily can have 100 profiles to recompile). aa-clickhook tries hard to only recompile when necessary and this branch should not regress on this point.

**Comment by mvo5** [comment]
On Mon, Nov 09, 2015 at 02:18:53PM -0800, jdstrand wrote:
> Something isn't quite right here. If I install hello-world, then update /var/lib/apparmor/profiles/click_hello-world.canonical_sh_1.0.18 to have an additional rule, then this isn't returning non-zero:
> $ sudo /tmp/snappy policygen --compare /apps/hello-world.canonical/current/meta/package.yaml  && echo "$?"
> 0
> 
> To ease working on the branch, I am going to commit it to the security.cleanup branch though.

Did you modify
 /var/lib/apparmor/profiles/click_hello-world.canonical_sh_1.0.18 ?
This is no longer the path used with this branch, the new path is:
 /var/lib/*snappy*/apparmor/profiles/...

I tested with this branch and it is working for me with my latest
  feature/native-security-policygen-regen
branch.

But that reminds me, where is the search path defined so that
apparmor_parser finds the new location of the profile? It seems to be
working but it would be nice for me to know where its defined.

Cheers,
 Michael

**Comment by mvo5** [comment]
On Mon, Nov 09, 2015 at 02:28:12PM -0800, jdstrand wrote:
> The idea with apparmor_parser -p is that *if* apparmor changed, then
> if the policy in /var/lib/snappy/apparmor/profiles is the *same* as
> what policy generation would create, then do a 'deep check' and see
> if 'apparmor_parser -p <old>' and 'apparmor_parser -p <current>' are
> different. This is because the parser or the included abstractions
> might have changed and there is no way to detect that without
> apparmor_parser -p (not, apparmor_parser -p is not a policy compile,
> it is a fast preprocessor that can be thought of as a normalized
> concatenation of the specified policy and all of the included
> abstractions). The only wrinkle with this is that '<old>' must be
> saved off as part as policy generation so that it can be compared to
> later.
[..]

Thanks a bunch. I'm happy to implement this, however:

I'm puzzled, how can:

"apparmor_parse -p <old>"
and
"apparmor_parse -p <new>"

return different results if the inputs <old> and <new> are identical?

It seems like we need to store the result (or hash) of "apparmor_parse
-p <old>" at the time that we actually create the policy for the first
time and compare that result (or hash) to "apparmor_parse -p <new>"
when a new appamor is installed. Or what am I missing here ?

Cheers,
 Michael

**Comment by jdstrand** [comment]
On 11/10/2015 05:36 AM, Michael Vogt wrote:
> On Mon, Nov 09, 2015 at 02:28:12PM -0800, jdstrand wrote:
>> The idea with apparmor_parser -p is that *if* apparmor changed, then
>> if the policy in /var/lib/snappy/apparmor/profiles is the *same* as
>> what policy generation would create, then do a 'deep check' and see
>> if 'apparmor_parser -p <old>' and 'apparmor_parser -p <current>' are
>> different. This is because the parser or the included abstractions
>> might have changed and there is no way to detect that without
>> apparmor_parser -p (not, apparmor_parser -p is not a policy compile,
>> it is a fast preprocessor that can be thought of as a normalized
>> concatenation of the specified policy and all of the included
>> abstractions). The only wrinkle with this is that '<old>' must be
>> saved off as part as policy generation so that it can be compared to
>> later.
> [..]
> 
> Thanks a bunch. I'm happy to implement this, however:
> 
> I'm puzzled, how can:
> 
> "apparmor_parse -p <old>"
> and
> "apparmor_parse -p <new>"
> 
> return different results if the inputs <old> and <new> are identical?
> 
> It seems like we need to store the result (or hash) of "apparmor_parse
> -p <old>" at the time that we actually create the policy for the first
> time and compare that result (or hash) to "apparmor_parse -p <new>"
> when a new appamor is installed. Or what am I missing here ?
> 
That is what I was getting at when I said "The only wrinkle with this is that
'<old>' must be saved off as part as policy generation so that it can be
compared to later." Ie, whenever the policy is generated and written out to
disk, we should as part of the last step do apparmor_parser -p <current> and
save that somewhere. Should this be a hash or the full file? hash is cleaner,
but it will be slower on arm-- I think 'diff old new || regenerate' is what we
want-- it'll be fast. Also, I don't think these files need to be easily
discoverable (ie, it is probably good to put them in a hidden directory, perhaps
/var/lib/snappy/apparmor/.compare (or something).

Furthermore, this check only needs to happen when apparmor itself changes:
'--compare' could gain a '--deep' option and the systemd unit would only add
'--regenerate-all --deep' if apparmor version changed, otherwise just
'--regenerate-all' if the others changed. Eg for systemd unit:

pkgs="ubuntu-core-security-apparmor ubuntu-core-security-seccomp
ubuntu-personal-security-apparmor ubuntu-personal-security-seccomp"

changed=
for p in pkgs ; do
    if [ p changed ]; then
        changed="yes"
    fi
done

if [ apparmor version changed ]; then
    snappy policygen --regenerate-all --deep
elif [ "$changed" = "yes" ]; then
    snappy policygen --regenerate-all
else
    echo "Nothing to do!"
fi


-- 
Jamie Strandboge             | http://www.ubuntu.com

**Comment by jdstrand** [comment]
On 11/10/2015 03:44 AM, Michael Vogt wrote:
> On Mon, Nov 09, 2015 at 02:18:53PM -0800, jdstrand wrote:
>> Something isn't quite right here. If I install hello-world, then update
> /var/lib/apparmor/profiles/click_hello-world.canonical_sh_1.0.18 to have an
> additional rule, then this isn't returning non-zero:
>> $ sudo /tmp/snappy policygen --compare
> /apps/hello-world.canonical/current/meta/package.yaml && echo "$?"
>> 0
>>
>> To ease working on the branch, I am going to commit it to the security.cleanup
> branch though.
> 
> Did you modify
> /var/lib/apparmor/profiles/click_hello-world.canonical_sh_1.0.18 ?
> This is no longer the path used with this branch, the new path is:
> /var/lib/*snappy*/apparmor/profiles/...

I know. I modified /var/lib/snappy/apparmor/profiles/...

> 
> I tested with this branch and it is working for me with my latest
> feature/native-security-policygen-regen
> branch.
> 
I was sideloading and also noticed I had non-sideloaded versions-- it is
possible I was hitting some problems with an unclean environment. I'll be
looking at this as part of my testing in a clean environment.

> But that reminds me, where is the search path defined so that
> apparmor_parser finds the new location of the profile? It seems to be
> working but it would be nice for me to know where its defined.
> 
This is in apparmor itself and it is only working on install because snappy is
calling apparmor_parser directly. On reboot, these profiles shouldn't be loading
right now. I'll adjust apparmor to handle that. Note, the systemd unit that
calls --regenerate-all needs to run *before* the apparmor unit.

-- 
Jamie Strandboge             | http://www.ubuntu.com

**Pull request merged**
